<?php
    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        $registro = 0;
        $name = $_POST["name"];
        $cpf = $_POST["cpf"];
        $uf = $_POST["uf"];
        $cep = $_POST["cep"];
        $fax = $_POST["fax"];
        $cel = $_POST["cel"];
        $datanas = $_POST["datanas"];
        $cidade = $_POST["cidade"];
        $bairro = $_POST["bairro"];
        $end = $_POST["end"];
        $web = $_POST["web"];
        $nomecom = $_POST["namecom"];
        $esc = $_POST["esc"];
        $tec = isset($_POST["tec"]) ? $_POST["tec"] : "";
        $esportes = isset($_POST["esportes"]) ? $_POST["esportes"] : "";
        $moda = isset($_POST["Moda"]) ? $_POST["Moda"] : "";
        $viagem = isset($_POST["Viagem"]) ? $_POST["Viagem"] : "";
        $edu = isset($_POST["Educacao"]) ? $_POST["Educacao"] : "";
        $jogos = isset($_POST["Jogos"]) ? $_POST["Jogos"] : "";
        $Economia = isset($_POST["Economia"]) ? $_POST["Economia"] : "";
        $tempo = isset($_POST["Tempo"]) ? $_POST["Tempo"] : "";
        $Policial = isset($_POST["Policial"]) ? $_POST["Policial"] : "";
        $Politica = isset($_POST["Politica"]) ? $_POST["Politica"] : "";
        $Automotiveis = isset($_POST["Automotiveis"]) ? $_POST["Automotiveis"] : "";
        $Cultura = isset($_POST["Cultura"]) ? $_POST["Cultura"] : "";
        $Culinaria = isset($_POST["Culinaria"]) ? $_POST["Culinaria"] : "";
        $email = $_POST["email"];
        $Empregos = isset($_POST["Empregos"]) ? $_POST["Empregos"] : ""; 
        $email = $_POST["email"];
        $tel = $_POST["tel"];
        $handle = fopen("bancodedados.txt", "a");
        fwrite($handle, "Registro nº$registro");
        fwrite($handle,"Nome: $name\n");
        fwrite($handle, "Nome completo: $nomecom\n");
        fwrite($handle, "CPf: $cpf\n");
        fwrite($handle, "Email: $email\n");
        fwrite($handle, "WebSite: $web\n");
        fwrite($handle, "Endereco: $end\n");
        fwrite($handle, "Bairro: $bairro\n");
        fwrite($handle, "CEP: $cep\n");
        fwrite($handle, "Telfone: $tel\n");
        fwrite($handle, "data de nascimento: $datanas\n");
        fwrite($handle, "Celular : $cel\n");
        fwrite($handle, "Cidade : $cidade\n");
        fwrite($handle, "Uf:$uf\n");
        fwrite($handle, "Fax:$fax\n");
        fwrite($handle, "Estado Civil:$esc\n");
        fwrite($handle, "tec : $tec\n");
        fwrite($handle, "Esportes:$esportes\n");
        fwrite($handle, "Automoveis : $Automotiveis\n");
        fwrite($handle, "Culinaria:$Culinaria\n");
        fwrite($handle, "Politica :$Politica \n");
        fwrite($handle, "Policial :$Policial \n");
        fwrite($handle, "Tempo : $tempo \n");
        fwrite($handle, "Cultura : $Cultura \n");
        fwrite($handle, "Economia : $Economia\n");
        fwrite($handle, "Jogos : $jogos\n");
        fwrite($handle, "Educacao : $edu \n");
        fwrite($handle, "Viagem : $viagem \n");
        fwrite($handle, "Empregos : $Empregos \n");
        fwrite($handle, "Moda : $moda \n");
        fclose($handle);
    }
?>